sudo: true
language: cpp

compiler:
  - gcc

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost1.55-all-dev

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

script: 
 # There is a difference in versions
 - $CXX --version
 - g++ --version
 - qmake TestConceptMapConsole.pro
 - cat Makefile
 - make
 - qmake TestConceptMapDesktop.pro
 - cat Makefile
 - make
